using System.Collections.Immutable;

namespace JorgeCostaMacia.Exception.Domain;

/// <summary>
/// Represents a domain exception that encapsulates one or more general error messages.
/// Typically used for aggregated, business, or service-level domain errors
/// that are not related to validation constraints.
/// </summary>
/// <remarks>
/// <para>
/// Inherit from this class for exceptions that need to capture multiple generic
/// or business logic errors occurring during domain or application operations.
/// </para>
///
/// <para>Properties include:</para>
/// <list type="bullet">
///    <item><description><see cref="Errors"/>: Immutable list of string messages that describe the errors.</description></item>
///    <item><description>Inherited metadata from <see cref="DomainException"/>: <see cref="DomainException.AggregateId"/>, <see cref="DomainException.AggregateType"/>, <see cref="DomainException.AggregateCode"/>, <see cref="DomainException.AggregateHttpCode"/>, and <see cref="DomainException.AggregateOccurredAt"/>.</description></item>
/// </list>
///
/// <para>
/// Constructors allow automatic formatting of the exception message to include
/// all error messages using the semi-colon (;) separator, as well as optional automatic generation of metadata
/// such as IDs, timestamps, and HTTP codes, leveraging the <see cref="DomainExceptionDefaults"/> and <see cref="ErrorExceptionDefaults"/> classes.
/// </para>
/// </remarks>
public abstract class ErrorException : DomainException
{
    /// <summary>
    /// Immutable list of error messages describing the reasons for this exception.
    /// </summary>
    public ImmutableList<string> Errors { get; init; }

    /// <summary>
    /// Constructor with explicit metadata and error messages.
    /// </summary>
    /// <param name="aggregateId">Unique identifier of this exception instance.</param>
    /// <param name="aggregateType">Full type name of the exception.</param>
    /// <param name="aggregateCode">Unique code representing the specific domain error.</param>
    /// <param name="aggregateHttpCode">HTTP status code associated with this error.</param>
    /// <param name="aggregateOccurredAt">Timestamp of when this exception occurred.</param>
    /// <param name="message">Optional exception message passed to the base <see cref="System.Exception"/>.</param>
    /// <param name="innerException">Inner exception, if any.</param>
    /// <param name="errors">Immutable list of error messages to be stored in the <see cref="Errors"/> property.</param>
    protected ErrorException(
        Guid aggregateId,
        string aggregateType,
        Guid aggregateCode,
        int aggregateHttpCode,
        DateTime aggregateOccurredAt,
        string? message,
        System.Exception? innerException,
        ImmutableList<string> errors
    ) : base(
        aggregateId,
        aggregateType,
        aggregateCode,
        aggregateHttpCode,
        aggregateOccurredAt,
        message,
        innerException
    )
    {
        Errors = errors;
    }

    /// <summary>
    /// Constructor with optional metadata, automatically generating IDs and formatting the message
    /// from the provided list of errors.
    /// </summary>
    /// <param name="aggregateId">Optional unique identifier of this exception instance. Defaults to a new GUID using <see cref="JorgeCostaMacia.GuidFactory.Domain.GuidFactory.Create()"/> if null.</param>
    /// <param name="aggregateType">Optional full type name of the exception. Defaults to the constant <see cref="ErrorExceptionDefaults.AGGREGATE_TYPE"/> if null.</param>
    /// <param name="aggregateCode">Optional unique code representing the specific domain error. Defaults to the constant <see cref="ErrorExceptionDefaults.AGGREGATE_CODE"/> if null.</param>
    /// <param name="aggregateHttpCode">Optional HTTP status code associated with this error. Defaults to the constant <see cref="ErrorExceptionDefaults.AGGREGATE_HTTP_CODE"/> (400) if null.</param>
    /// <param name="aggregateOccurredAt">Optional timestamp of when this exception occurred. Defaults to <see cref="DateTime.UtcNow"/> if null.</param>
    /// <param name="message">Optional exception message. If omitted or null, the message is generated by joining the elements in the <paramref name="errors"/> list with a semi-colon (;).</param>
    /// <param name="innerException">Inner exception, if any.</param>
    /// <param name="errors">List of error messages used to initialize the <see cref="Errors"/> property and format the exception message.</param>
    protected ErrorException(
        Guid? aggregateId,
        string? aggregateType,
        Guid? aggregateCode,
        int? aggregateHttpCode,
        DateTime? aggregateOccurredAt,
        string? message,
        System.Exception? innerException,
        IEnumerable<string> errors
    ) : base(
        aggregateId,
        aggregateType ?? ErrorExceptionDefaults.AGGREGATE_TYPE,
        aggregateCode ?? ErrorExceptionDefaults.AGGREGATE_CODE,
        aggregateHttpCode ?? ErrorExceptionDefaults.AGGREGATE_HTTP_CODE,
        aggregateOccurredAt,
        $"{message ?? string.Join("; ", errors)}",
        innerException
    )
    {
        Errors = errors.ToImmutableList();
    }
}
