using System.Collections.Immutable;
using FluentValidation.Results;

namespace JorgeCostaMacia.Exception.Domain;

/// <summary>
/// Represents a domain exception that occurs due to validation constraints violations.
/// Contains details of all failed validations.
/// </summary>
/// <remarks>
/// <para>
/// Inherit from this class for exceptions that need to capture validation errors,
/// typically using <see cref="ValidationFailure"/> or related validation libraries.
/// </para>
///
/// <para>Properties include:</para>
/// <list type="bullet">
///    <item><description><see cref="Validations"/>: Immutable list of <see cref="ValidationFailure"/> objects that triggered this exception.</description></item>
///    <item><description>Inherited metadata from <see cref="DomainException"/>: <see cref="DomainException.AggregateId"/>, <see cref="DomainException.AggregateType"/>, <see cref="DomainException.AggregateCode"/>, <see cref="DomainException.AggregateHttpCode"/>, and <see cref="DomainException.AggregateOccurredAt"/>.</description></item>
/// </list>
///
/// <para>
/// The optional constructor automatically formats the exception message to include
/// all validation errors, as well as optional automatic generation of metadata
/// such as IDs, timestamps, and HTTP codes, defaulting to <b>400 (Bad Request)</b>.
/// </para>
/// </remarks>
public abstract class ValidationException : DomainException
{
    /// <summary>
    /// Immutable list of validation failures that caused this exception.
    /// Each item typically contains the member name and the error message.
    /// </summary>
    public ImmutableList<ValidationFailure> Validations { get; init; }

    /// <summary>
    /// Constructor with explicit metadata and validation failures.
    /// Provides full control over all base exception properties and the list of constraints.
    /// </summary>
    /// <param name="aggregateId">Unique identifier of this exception instance. (Required)</param>
    /// <param name="aggregateType">Full type name of the exception. (Required)</param>
    /// <param name="aggregateCode">Unique code representing the specific domain error. (Required)</param>
    /// <param name="aggregateHttpCode">HTTP status code associated with this error (e.g., 400).</param>
    /// <param name="aggregateOccurredAt">Timestamp of when this exception occurred.</param>
    /// <param name="message">Optional exception message passed to the base <see cref="System.Exception"/>.</param>
    /// <param name="innerException">Inner exception, if any.</param>
    /// <param name="validations">Immutable list of validation failures to be stored in the <see cref="Validations"/> property.</param>
    protected ValidationException(
        Guid aggregateId,
        string aggregateType,
        Guid aggregateCode,
        int aggregateHttpCode,
        DateTime aggregateOccurredAt,
        string? message,
        System.Exception? innerException,
        ImmutableList<ValidationFailure> validations
    ) : base(aggregateId, aggregateType, aggregateCode, aggregateHttpCode, aggregateOccurredAt, message, innerException)
    {
        Validations = validations;
    }

    /// <summary>
    /// Constructor with optional metadata, automatically generating IDs and formatting the message
    /// from the validation failures, leveraging <see cref="ValidationExceptionDefaults"/>.
    /// </summary>
    /// <param name="aggregateId">Optional unique identifier of this exception instance. Defaults to a new GUID using <see cref="JorgeCostaMacia.GuidFactory.Domain.GuidFactory.Create()"/> if null.</param>
    /// <param name="aggregateType">Optional full type name of the exception. Defaults to <see cref="ValidationExceptionDefaults.AGGREGATE_TYPE"/> if null.</param>
    /// <param name="aggregateCode">Optional unique code representing the specific domain error. Defaults to the fixed GUID from <see cref="ValidationExceptionDefaults.AGGREGATE_CODE"/> if null.</param>
    /// <param name="aggregateHttpCode">Optional HTTP status code associated with this error. Defaults to 400 (Bad Request) from <see cref="ValidationExceptionDefaults.AGGREGATE_HTTP_CODE"/> if null.</param>
    /// <param name="aggregateOccurredAt">Optional timestamp of when this exception occurred. Defaults to <see cref="DateTime.UtcNow"/> if null.</param>
    /// <param name="message">
    /// Optional exception message. If omitted or null, the message is generated by concatenating each
    /// validation failure's <see cref="ValidationFailure.PropertyName"/> and <see cref="ValidationFailure.ErrorMessage"/>
    /// (separated by a colon), joining multiple validation failures with semicolons.
    /// </param>
    /// <param name="innerException">Inner exception, if any.</param>
    /// <param name="validations">List of validation failures used to initialize the <see cref="Validations"/> property and format the exception message.</param>
    protected ValidationException(
        Guid? aggregateId,
        string? aggregateType,
        Guid? aggregateCode,
        int? aggregateHttpCode,
        DateTime? aggregateOccurredAt,
        string? message,
        System.Exception? innerException,
        IEnumerable<ValidationFailure> validations
    ) : base(
        aggregateId,
        aggregateType ?? ValidationExceptionDefaults.AGGREGATE_TYPE,
        aggregateCode ?? ValidationExceptionDefaults.AGGREGATE_CODE,
        aggregateHttpCode ?? ValidationExceptionDefaults.AGGREGATE_HTTP_CODE,
        aggregateOccurredAt,
        $"{message ?? string.Join("; ", validations.Select(e => e.PropertyName + ": " + e.ErrorMessage))}",
        innerException
    )
    {
        Validations = validations.ToImmutableList();
    }
}
